project:
  type: website
  output-dir: docs
  
website: 
  page-navigation: true
  reader-mode: false
  title: "Bren's Networking Notes" 
  site-url: "https://brunbattery.github.io/NetworkNotes/" 
  
  page-footer:
    background: primary
    right: "Published by Brendan Battersby, 2023"
    left: ""
    
  sidebar:
    background: dark
    logo: ""
    pinned: true
    align: center
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/brendanbattersby/
        text: "LinkedIn"
      - icon: youtube
        href: https://www.youtube.com/@brunbattery
        text: "YouTube"


    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - section: Security
        contents: 
          - IPsec.md
      - section: Routing
        contents: 
          - BGP.md

format:
  html:
    theme: solar
    fontsize: 1.1em
    monofontcolor: rgb(185, 143, 13)
    monobackgroundcolor: rgb (185, 143, 13)


filters:
  - quarto